apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycapstone1
  labels:
    app: mycapstone1
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mycapstone1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: mycapstone1
    spec:
      containers:
        - image: shashank81jain/capstonedocker3
          imagePullPolicy: Always
          name: mycapstone1
          ports:
            - containerPort: 80
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /
              port: 80